Repository nukeop/nuclear, pull requests merged in 2019-12, with the labels that each got.

#560 fix(plugin): fix format filter in Youtube plugin
  packages/app/app/plugins/stream/YoutubePlugin.js
Labels: bug

#571 Fix/local library
  .eslintrc.json
  package.json
  packages/app/app/components/LibraryView/NoApi/index.js
  packages/app/app/components/LibraryView/NoApi/styles.scss
  packages/app/app/components/LibraryView/index.js
  packages/app/app/containers/LibraryViewContainer/index.js
  packages/app/app/locales/cs.json
  packages/app/app/locales/en.json
  packages/app/app/locales/es.json
  packages/app/app/locales/fr.json
  packages/app/app/locales/id.json
  packages/app/app/locales/it.json
  packages/app/app/locales/ko.json
  packages/app/app/locales/pl.json
  packages/app/app/locales/sk.json
  packages/app/app/locales/sq.json
  packages/app/app/locales/tl.json
  packages/app/app/locales/tr.json
  packages/app/app/plugins/stream/LocalPlugin.js
  packages/app/app/rest/Local.js
  packages/app/package.json
  packages/main/src/controllers/local-library.ts
  packages/main/src/services/http/index.ts
  packages/main/src/services/http/server/api/index.ts
  packages/main/src/services/http/server/api/localfile.ts
  packages/main/src/services/local-library/db.ts
  packages/main/src/services/local-library/index.ts
  packages/main/src/services/system-api/linux.ts
  packages/ui/.eslintrc.json
  packages/ui/lib/components/AlbumGrid/index.js
  packages/ui/stories/.eslintrc.json
  packages/ui/stories/index.stories.js
  packages/ui/stories/queueItem.stories.js
  packages/ui/stories/toasts.stories.js
  packages/ui/stories/trackRow.stories.js
Labels: bug, enhancement

#573 Refactor/app log flood
  packages/app/.eslintrc.json
  packages/app/app/components/AlbumCover/AlbumInfo/index.js
  packages/app/app/components/AlbumCover/AlbumInfo/styles.scss
  packages/app/app/components/AlbumCover/AlbumOverlay/index.js
  packages/app/app/components/AlbumCover/AlbumOverlay/styles.scss
  packages/app/app/components/AlbumCover/index.js
  packages/app/app/components/AlbumCover/styles.scss
  packages/app/app/components/Dashboard/BestNewMusicTab/index.js
  packages/app/app/components/Dashboard/GenresTab/index.js
  packages/app/app/components/Settings/index.js
  packages/app/app/components/TagView/TagTopList/index.js
  packages/app/app/components/VolumeControls/VolumeSlider/index.js
  packages/app/app/components/WindowControls/WindowButton/index.js
  packages/app/app/components/WindowControls/WindowButton/styles.scss
  packages/app/app/components/WindowControls/index.js
  packages/app/app/components/WindowControls/styles.scss
  packages/app/app/containers/ErrorBoundary/index.js
  packages/app/app/index.js
  packages/app/index.html
  packages/app/package.json
  packages/app/webpack.config.js
  packages/main/preload.js
  packages/main/src/services/window/index.ts
  packages/main/webpack.config.ts
  packages/ui/.babelrc
  packages/ui/lib/components/Card/index.js
  packages/ui/lib/components/Range/index.js
  packages/ui/lib/components/Range/index.scss
  packages/ui/lib/components/SmoothImage/index.js
  packages/ui/lib/components/SmoothImage/styles.scss
  packages/ui/lib/index.js
  tsconfig.json
Labels: bug, enhancement

#564 (#536) Clear progress bar when queue is cleared
  packages/app/app/App.js
  packages/app/app/actions/player.js
  packages/app/app/components/PlayQueue/QueueMenu/QueueMenuMore/index.js
  packages/app/app/components/PlayQueue/QueueMenu/index.js
  packages/app/app/components/PlayQueue/index.js
  packages/app/app/containers/PlayQueueContainer/index.js
  packages/app/app/containers/ShortcutsContainer/index.js
  packages/app/app/containers/SoundContainer/index.js
  packages/app/app/mpris.js
  packages/app/test/enzyme.queuemenumore.test.js
  packages/app/test/integration/queueplayer.test.js
  packages/ui/lib/components/QueueItem/index.js
Labels: under review

#576 MacOs media service and build improvement
  .gitattributes
  packages/app/app/mpris.js
  packages/main/config/tsconfig.linux.json
  packages/main/config/tsconfig.mac.json
  packages/main/config/tsconfig.windows.json
  packages/main/package.json
  packages/main/src/controllers/player.ts
  packages/main/src/controllers/settings.ts
  packages/main/src/interfaces/nuclear-api.ts
  packages/main/src/ioc.ts
  packages/main/src/main.ts
  packages/main/src/services/@linux/system-api.ts
  packages/main/src/services/@mac/system-api.ts
  packages/main/src/services/@windows/system-api.ts
  packages/main/src/services/http/server/middlewares.ts
  packages/main/src/services/local-library/db.ts
  packages/main/src/services/system-api/index.ts
  packages/main/src/services/system-api/mac.ts
  packages/main/src/services/system-api/win.ts
  packages/main/src/utils/decorators.ts
  packages/main/src/utils/types.ts
  packages/main/typings/electron-media-service.d.ts
  packages/main/typings/electron-timber.d.ts
  packages/main/webpack.config.ts
Labels: enhancement

#579 fix(mpris): fix clearQueue behavior
  packages/app/app/actions/queue.js
  packages/app/app/mpris.js
  packages/main/src/controllers/player.ts
  packages/main/src/interfaces/nuclear-api.ts
  packages/main/src/services/@linux/system-api.ts
Labels: bug

#582 Fix/download
  packages/main/.env
  packages/main/src/controllers/download.ts
  packages/main/src/controllers/settings.ts
  packages/main/src/main.ts
  packages/main/src/services/config/index.ts
  packages/main/src/services/download/index.ts
  packages/main/src/services/store/index.ts
  packages/main/src/services/window/index.ts
  packages/main/typings/env.d.ts
Labels: bug
